#--------------------- DB Connection ------------------
spring.datasource.url=jdbc:h2:mem:jwtdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (http://localhost:8081/h2-console)
spring.h2.console.enabled=true

#--------------------JPA-ORM Properties-----------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl = true

#---------------------------Jwt--------------------------

toyota.app.secret=toyotabackend
toyota.expires.in=86400000


server.port=8081
